---
# Organization Details
org:
  name: "bitYoga"
  unit: "devops"

# Users and groups that would be created on host machines, for creating a swarm and deplying hlf services
docker_group: "docker"
docker_gid: "2001"

hlf_username: "hlf"
hlf_uid: "2002"
hlf_group: "hlf"
hlf_gid: "2002"

# Name of the swarm network that would host the services
swarm_network: "hlfnet"

# S3FS shared file system to store the services config and data
# S3FS on DigitalOcean
S3FS_URL: "https://fra1.digitaloceanspaces.com"
S3FS_KEY: "5JWX4EJM5OCRY7AATWYU"
S3FS_SECRET: "3cM8A1JI/ZaP0+qZ//hbzcT2PUkPsXMMbzFiaOrphTA"

# Fabric Images and Services
rca: { image: "hyperledger/fabric-ca", tag: "1.4", name: "rca", uid: "3001", gid: "{{hlf_gid}}", group: "{{hlf_group}}" }
aica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "aica", uid: "3002", gid: "{{hlf_gid}}", group: "{{hlf_group}}" }
uica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "uica", uid: "3003", gid: "{{hlf_gid}}", group: "{{hlf_group}}" }

services:
  - "{{rca}}"
  - "{{aica}}"
  - "{{uica}}"

# Hyperledger Fabric CA related variables
ca:
  version: "0.1"
  cn: "hlf"
  country: "Norway"
  state: "Rogaland"
  city: "Stavanger"
  maxenrollments: -1
  allow_intermediate: true
  host: ""