---
# Organization Details
org:
  name: "bitYoga"
  unit: "hlf"

# Users and groups that would be created on host machines, for creating a swarm and deplying hlf services
docker_group: "docker"
docker_gid: "2001"

hlf_username: "hlf"
hlf_uid: "2002"
hlf_group: "hlf"
hlf_gid: "2002"

# Name of the swarm network that would host the services
swarm_network: "hlfnet"

# S3FS shared file system to store the services config and data
# S3FS on DigitalOcean
S3FS_URL: "https://fra1.digitaloceanspaces.com"
S3FS_KEY: "5JWX4EJM5OCRY7AATWYU"
S3FS_SECRET: "3cM8A1JI/ZaP0+qZ//hbzcT2PUkPsXMMbzFiaOrphTA"
  

# Fabric Images and Services
rca: { image: "hyperledger/fabric-ca", tag: "1.4", name: "rca",
 uid: "3001", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: true, pathlength: 1, port: 7054,
       username: "{{rca_username}}", password: "{{rca_password}}", affiliation: "{{org.name}}.{{org.unit}}", parent: "",
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "rca", country: "NO", state: "Rogaland", city: "Stavanger"},
 commands: "fabric-ca-server start"
 }

aica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "aica", 
uid: "3002", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: false, pathlength: 0, port: 7054,
       username: "{{aica_username}}", password: "{{aica_password}}", affiliation: "{{org.name}}.{{org.unit}}", parent: "{{rca.name}}",     
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"},
 commands: "fabric-ca-server start -u https://radmin:radminpw@rca:7054 --intermediate.tls.certfiles /home/aica/fabric-ca/ca-parent-cert.pem"
 }

uica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "uica", 
uid: "3003", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: 1, allow_intermediateca_registration: false, pathlength: 0, port: 7054,
       username: "{{uica_username}}", password: "{{uica_password}}", affiliation: "{{org.name}}.{{org.unit}}", parent: "{{rca.name}}",
       tls_enabled: false, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"},
 commands: "fabric-ca-server start -u http://{{rca_username}}:{{rca_password}}@{{rca.name}}:{{rca.ca.port}}" 
 }

services:
  - "{{rca}}"
  - "{{aica}}"
  #- "{{uica}}"

# Hyperledger Fabric CA related variables
cas:
  - "{{rca}}"
  - "{{aica}}"
  #- "{{uica}}"