---
# Organization Details
org:
  name: "bitYoga"
  unit: "hlf"

# Users and groups that would be created on host machines, for creating a swarm and deplying hlf services
docker_group: "docker"
docker_gid: "2001"

hlf_username: "hlf"
hlf_uid: "2002"
hlf_group: "hlf"
hlf_gid: "2002"

rca_user: "rca"
rca_uid: "3001"
aica_user: "aica"
aica_uid: "3002"
uica_user: "uica"
uica_uid: "3003"
psql_user: "postgres"
psql_uid: "3004"

# Name of the swarm network that would host the services
swarm_network: "hlfnet"

# S3FS shared file system to store the services config and data
# S3FS on DigitalOcean
S3FS_URL: "https://fra1.digitaloceanspaces.com"
S3FS_KEY: "5JWX4EJM5OCRY7AATWYU"
S3FS_SECRET: "3cM8A1JI/ZaP0+qZ//hbzcT2PUkPsXMMbzFiaOrphTA"
  

# Fabric Images and Services
rca: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{rca_user}}", replicas: -1,
 uid: "{{rca_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: true, pathlength: 1, port: 7054,
       affiliation: "{{org.name}}.{{org.unit}}", parent: "",
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "rca", country: "NO", state: "Rogaland", city: "Stavanger"}
 }

aica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{aica_user}}", replicas: -1,
uid: "{{aica_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: false, pathlength: 0, port: 7055,
       affiliation: "{{org.name}}.{{org.unit}}", parent: "{{rca.name}}",     
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"}
 }

uica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{uica_user}}", replicas: 2,
uid: "{{uica_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: 1, allow_intermediateca_registration: false, pathlength: 0, port: 7056,
       affiliation: "{{org.name}}.{{org.unit}}", parent: "{{rca.name}}",
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"}
 }

psql: { image: "postgres", tag: "12-alpine", name: "{{psql_user}}", replicas: -1,
uid: "{{psql_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", tls_enabled: true, 
listen_addresses: "localhost", port: 5432
}

cacreds: {
      rca: {name: "{{rca.name}}", username: "{{rca_username}}", password: "{{rca_password}}",
           commands: "fabric-ca-server start" },
      aica: {name: "{{aica.name}}", username: "{{aica_username}}", password: "{{aica_password}}",
            commands: "fabric-ca-server start -u https://{{rca_username}}:{{rca_password}}@rca:{{rca.ca.port}} --intermediate.tls.certfiles /home/aica/fabric-ca/ca-{{rca.name}}-cert.pem"},
      uica: {name: "{{aica.name}}", username: "{{aica_username}}", password: "{{aica_password}}",
            commands: "fabric-ca-server start -u https://{{rca_username}}:{{rca_password}}@rca:{{rca.ca.port}} --intermediate.tls.certfiles /home/aica/fabric-ca/ca-{{rca.name}}-cert.pem" },
      psql: {name: "{{psql.name}}", username: "{{psql_username}}", password: "{{psql_password}}",
            commands: "sleep 30000" }
}

services:
  - "{{rca}}"
  - "{{aica}}"
  - "{{uica}}"
  - "{{psql}}"
  