---
# Organization Details
org:
  name: "bityoga"
  unit: "hlf"

# Users and groups that would be created on host machines, for creating a swarm and deplying hlf services
docker_group: "docker"

hlf_username: "hlf"
hlf_uid: "2002"
hlf_group: "hlf"
hlf_gid: "2002"

rca_user: "rca"
rca_uid: "3001"
aica_user: "aica"
aica_uid: "3002"
uica_user: "uica"
uica_uid: "3003"
orderer_user: "orderer"
orderer_uid: "3004"
epeer_user: "epeer"
epeer_uid: "3006"
cpeer_user: "cpeer"
cpeer_uid: "3007"
apeer_user: "apeer"
apeer_uid: "3008"
epeerdb_user: "epeerdb"
epeerdb_uid: "4001"

rca_password: "radminpw"
aica_password: "aiadminpw"    
uica_password: "uiadminpw"
orderer_password: "oadminpw"
epeer_password: "epadminpw"
cpeer_password: "cpadminpw"
apeer_password: "apadminpw"

# Name of the swarm network that would host the services
swarm_network: "hlfnet"

# S3FS shared file system to store the services config and data
# S3FS on DigitalOcean
S3FS_URL: "https://fra1.digitaloceanspaces.com"
S3FS_KEY: "5JWX4EJM5OCRY7AATWYU"
S3FS_SECRET: "3cM8A1JI/ZaP0+qZ//hbzcT2PUkPsXMMbzFiaOrphTA"

sqlite: {type: "sqlite3", source: "fabric-ca-server.db"}


# Fabric Images and Services
rca: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{rca_user}}", replicas: -1,
 uid: "{{rca_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: true, pathlength: 1, port: 7054,
       affiliation: "{{org.name}}.{{org.unit}}", parent: "",
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "rca", country: "NO", state: "Rogaland", city: "Stavanger"}, 
 path: "/home/{{ hlf_username }}/hlft-store/{{rca_user}}",
 db: "{{sqlite}}",
 password: "{{rca_password}}"
 }

aica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{aica_user}}", replicas: -1,
uid: "{{aica_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: -1, allow_intermediateca_registration: false, pathlength: 0, port: 7055,
       affiliation: "{{org.name}}.{{org.unit}}.agents", parent: "{{rca.name}}",     
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"}, 
 path: "/home/{{ hlf_username }}/hlft-store/{{aica_user}}",
 db: "{{sqlite}}",
 password: "{{aica_password}}"
 }

uica: { image: "hyperledger/fabric-ca", tag: "1.4", name: "{{uica_user}}", replicas: 2,
uid: "{{uica_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}",
 ca: { version: "0.1", maxenrollments: 1, allow_intermediateca_registration: false, pathlength: 0, port: 7056,
       affiliation: "{{org.name}}.{{org.unit}}.users", parent: "{{rca.name}}",
       tls_enabled: true, tls_clientauth_type: "noclientcert"},
 csr: {cn: "", country: "NO", state: "Rogaland", city: "Stavanger"}, 
 path: "/home/{{ hlf_username }}/hlft-store/{{uica_user}}",
 db: "{{sqlite}}",
 password: "{{uica_password}}"
 }

orderer: { image: "hyperledger/fabric-orderer", tag: "1.4", name: "{{orderer_user}}", replicas: -1,
uid: "{{orderer_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", port: 6050,
caname: "{{aica.name}}", anchorpeer: "{{apeer.name}}", anchorport: "{{apeer.port}}",
path: "/home/{{ hlf_username }}/hlft-store/{{orderer_user}}",
 password: "{{orderer_password}}"
}

epeer: { image: "hyperledger/fabric-peer", tag: "1.4", name: "{{epeer_user}}", replicas: -1,
uid: "{{epeer_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", port: 7050,
caname: "{{aica.name}}", bootstrap_peers: {"{{cpeer.name}}:{{cpeer.port}}", "{{apeer.name}}:{{apeer.port}}"},
path: "/home/{{ hlf_username }}/hlft-store/{{epeer_user}}", 
dbtype: "goleveldb", couchdbaddress: "",
password: "{{epeer_password}}",
leader: "{{cpeer_user}}"
}

cpeer: { image: "hyperledger/fabric-peer", tag: "1.4", name: "{{cpeer_user}}", replicas: -1,
uid: "{{cpeer_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", port: 8050,
caname: "{{aica.name}}", bootstrap_peers: {"{{epeer.name}}:{{epeer.port}}", "{{apeer.name}}:{{apeer.port}}"},
path: "/home/{{ hlf_username }}/hlft-store/{{cpeer_user}}", 
dbtype: "goleveldb", couchdbaddress: "",
password: "{{cpeer_password}}",
leader: "{{cpeer_user}}"
}

apeer: { image: "hyperledger/fabric-peer", tag: "1.4", name: "{{apeer_user}}", replicas: -1,
uid: "{{apeer_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", port: 9050,
caname: "{{aica.name}}", bootstrap_peers: {"{{epeer.name}}:{{epeer.port}}", "{{cpeer.name}}:{{cpeer.port}}"},
path: "/home/{{ hlf_username }}/hlft-store/{{apeer_user}}", 
dbtype: "goleveldb", couchdbaddress: "",
password: "{{apeer_password}}",
leader: "{{cpeer_user}}"
}

epeerdb: { image: "hyperledger/fabric-couchdb", tag: "0.4.15", name: "{{epeerdb_user}}", replicas: -1,
uid: "{{epeerdb_uid}}", gid: "{{hlf_gid}}", group: "{{hlf_group}}", port: 7051,
path: "/home/{{ hlf_username }}/hlft-store/{{epeerdb_user}}",
commands: 
"sleep 5s;
/opt/couchdb/bin/couchdb;"
}

services:
  - "{{rca}}"
  - "{{aica}}"
  - "{{uica}}"  
  - "{{orderer}}"
  - "{{ epeer }}"    
  - "{{ cpeer }}"    
  - "{{ apeer }}"
  - "{{ epeerdb }}"      