---

- name: Update and upgrade apt packages
  become: yes
  apt:
    #upgrade: yes
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Update and upgrade yum packages
  become: yes
  yum:
    #upgrade: yes
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Install prerequisites for Debian distros
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ debian_package_list }}"
  when: ansible_os_family == 'Debian'

- name: Install prerequisites for RedHat distros
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ redhat_package_list }}"
  when: ansible_os_family == 'RedHat'

- name: Install docker driver for python.
  pip:
    name: "{{ item }}"
  loop: "{{ pip_packages }}"