---
# ansible-playbook -v -001.despawn_droplets.yml

- name: create droplets
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - digital_ocean_droplet:    
        name: "{{item.name}}"
        oauth_token: 2c7eab4408ccb4f5805e68030f0482f1f2120ed6e9c04e11bb9b227b58d0fbef
        state: absent
        unique_name: yes
        wait: yes
        wait_timeout: 300  
      loop:
        - {name: "hlft0"} # Ubuntu 16.04.6 x64 20190713
        - {name: "hlft1"}
        - {name: "hlft2"}
        - {name: "hlft3"}
        - {name: "hlft4"}
      register: droplets
      
    # Delete the host file if present
    - file:
        path: ./inventory/hosts
        state: absent