---
# ansible-playbook -v 001.init.mount.yml -u root

- name: create mount
  hosts: swarm_manager_prime
  gather_facts: yes
  tasks:
  - name: Install nfs-kernel-server on prime
    become: yes
    apt:
      name: "nfs-kernel-server"
      state: present
      update_cache: yes
  
  - name: Create Mount Point
    become: yes
    file:
      path: /home/{{ hlf_username }}/hlft-store
      state: directory
      owner: "{{ hlf_username}}"
      group: "{{ hlf_group}}"
      mode: 0750
  
  - name: Update /etc/exports to export a folder
    lineinfile:
      state: present
      path: /etc/exports
      regexp: "/home/{{ hlf_username }}"
      line: /home/{{ hlf_username }}/hlft-store *(rw,sync,no_root_squash)

  - name: Start nfs-kernel-server service
    become: yes
    shell: 'service nfs-kernel-server restart'    
 