---

# ansible-playbook -v 011.initialize_hosts.yml -u root

- name: Initialize the host machines
  hosts: all
  gather_facts: yes
  roles:
    - init/common_packages
    - init/docker
    - init/post_installation