---

# ansible-playbook -v 015.despawn_swarm.yml -u root

- name: Despawn a docker swarm
  hosts: all
  gather_facts: no
  become: yes
  become_user: "{{ hlf_username }}"
  tasks:
    # Remove the nodes from the swarm network
    - docker_swarm:
        state: absent
      when: "inventory_hostname in groups.swarm_workers"

    # Remove the managers from the swarm network
    - docker_swarm:
        state: absent
        force: yes
      when: "inventory_hostname in groups.swarm_managers"

    # Delete the swarm network
    - docker_network:    
        name: "{{ swarm_network }}"
        state: absent
        force: yes
      when: "inventory_hostname in groups.swarm_manager_prime"
