---

# ansible-playbook -v 102.deploy_peers.yml --flush-cache -u root 

- name: Spawn a Hyperledger Fabric Topology
  hosts: swarm_manager_prime
  gather_facts: no
  vars:
    couchdb_password: {epeerdb: "epeerdbpw", cpeerdb: "cpeerdbpw", apeerdb: "apeerdbpw"}
  roles:
    - hlf/peer
    - hlf/cli     