---
- name: Test Playbook
  hosts: swarm_manager_prime
  gather_facts: no
  vars:
    Consenters: []
  tasks:
    - name: Build a list for all --csr.hosts
      vars:
        csrhostslist: "{{ caservices | map(attribute='name') | list + peerservices | map(attribute='name') | list  + [ orderer.name ] + [ cli.name ] + ['localhost'] + groups['swarm_managers'] | map('extract', hostvars, ['ansible_host']) | list }}"
      set_fact:
        csrhosts: "{{csrhostslist | join(',')}}"  
    
    - debug:
        msg: "{{csrhosts}}"