---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ ansible_loop.first }} --- {{ item[0].name }} - {{ item[1].name }}"
      with_nested:
        - "{{caservices}}"
        - "{{peerservices}}"
      loop_control:
        extended: yes
