---
- name: Test Playbook
  hosts: swarm_manager_prime
  gather_facts: true
  vars:
    Consenters: []
  tasks:
    # Generate the list of swarm managers to be used as Orderer Endpoints in configtx
    - name: Get IP addresses as a list for all swarm manager nodes
      vars:
        _swarm_manager_ip_list: "{{ groups['swarm_managers'] | map('extract', hostvars, ['ansible_host']) | list  | join(':{{orderer.port}},')  }}"            
        __swarm_manager_ip_list: "{{_swarm_manager_ip_list}}:{{orderer.port}}"
      set_fact:      
        swarm_manager_ip_list: "{{ __swarm_manager_ip_list.split(',') }}"

    - name: Test hosts list
      debug:
        msg: "{{ swarm_manager_ip_list }}"

    - name: Build a list of all consenter
      set_fact:
        Consenters: "{{ Consenters }} + [ {{ senter }} ]"
      vars:         
        senter: {Host: "{{item}}", Port: "{{orderer.port}}",ClientTLSCert: "{{orderer.path}}/msp/tls/server.crt",ServerTLSCert: "{{orderer.path}}/msp/tls/server.crt"}
      loop: "{{groups['swarm_managers'] | map('extract', hostvars, ['ansible_host']) | list}}"

    - name: Test consenters list
      debug:
        msg: "{{ Consenters }}"


    # Copy relevent config files to mount directories for the docker services
    - name: Config templating configtx.yaml
      become: yes  
      template:
        src: "configtx.yaml.j2"
        dest: "/root/hlft-store/configtx.yaml"
        mode: 0660
        force: yes  
  