---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - debug:
        msg: "[ IDX={{item.1.0}} - HOST_HOME={{item.0.path}} - FABRIC_CA_NAME={{item.0.name}} - FABRIC_CA_SECRET={{item.0.password}} - FABRIC_CA_PORT=7054 - CORE_PEER_LOCALMSPID={{org.name}}MSP - AGENT_HOST={{item.1.1.name}} - AGENT_SECRET={{item.1.1.password}} - AGENT_TYPE={{item.1.1.type}} ]"
      loop: "{{caservices | product(peerservices|enumerate) | list}}"
      
  