---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  tasks:      
    - debug:
        msg: "{{item.0.name}} - {{item.1}} - {{item.2}}"
      with_nested:
        - "{{peerservices}}"
        - [["tlscacerts/tls-{{tlsca.name}}-7054.pem", "ca.crt"],
         ["signcerts/cert.pem", "server.crt"],
         ["keystore/key.pem", "server.key"]]
  