---
- name: Test Playbook
  hosts: localhost
  gather_facts: no
  tasks:      
    - name: Get IP addresses as a list for all swarm manager nodes
      vars:
        _swarm_manager_ip_list: "{{ groups['swarm_managers'] | map('extract', hostvars, ['ansible_host']) | list  | join(':{{orderer.port}},')  }}"            
        __swarm_manager_ip_list: "{{_swarm_manager_ip_list}}:{{orderer.port}}"
      set_fact:      
        swarm_manager_ip_list: "{{ __swarm_manager_ip_list.split(',') }}"
    
    - debug:
        msg: "{{swarm_manager_ip_list}}"