# ---
# Stop all Bank App services
- name: Stop Bank App  Service - {{ item.name }}
  become: yes
  docker_swarm_service:
    name: "{{item.name}}"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop:
    - "{{bank_app}}"
  when: bank_app.switch == "on" and inventory_hostname in groups.swarm_manager_prime

  # Clean  bank-app files folders , if they exists
- name: Clean  bank-app files folders , if they exists
  become: yes
  file:
    path: "/root/articonf-bank-app/"
    state: absent
  when: bank_app.switch == "on"

  # git clone  bank-app files
- name: Git clone  bank-app files
  become: yes
  shell: git clone {{bank_app.git_repository}} /root/articonf-bank-app

  # Copy orderer tls certificate to bank app folder
- name: Copy orderer certificate to bank app folder
  become: yes
  shell: cp /root/hlft-store/{{orgca.name}}/{{orderer.name}}/msp/tls/ca.crt /root/articonf-bank-app/fabric_node_sdk_helper/hlft-store/{{orderer.name}}/tls-msp/tlscacerts/ca.crt

  # Copy peer2 tls certificate to bank app folder
- name: Copy peer2 certificate to bank app folder
  become: yes
  shell: cp /root/hlft-store/{{orgca.name}}/{{peer2.name}}/msp/tls/ca.crt /root/articonf-bank-app/fabric_node_sdk_helper/hlft-store/{{peer2.name}}/tls-msp/tlscacerts/ca.crt

# Template copy sdk network_config.json file
- name: Template copy sdk network_config.json file
  become: yes
  template:
    src: "sdk_network_connection_profile.json"
    dest: "/root/articonf-bank-app/fabric_node_sdk_helper/network_profile.json"
    mode: "0750"
    force: yes
  when: bank_app.switch == "on"

  # Build Docker Image
- name: Build Docker Image for bank app
  become: yes
  shell: cd /root/articonf-bank-app && bash build_docker_image.sh
  ignore_errors: yes

  # Run as docker service with replicas
# - name: Run as docker service with replicas
#   become: yes
#   shell: docker service create --name bank-service --replicas 1 -p 3000:3000 bank-app:latest


- name: Bank App Docker Service
  become: yes
  docker_swarm_service:
    name: "{{bank_app.name}}"
    hostname: "{{bank_app.name}}"
    networks:
      - "{{swarm_network}}"
    image: "{{bank_app.image}}:{{bank_app.tag}}"
    mode: replicated
    replicas: "{{bank_app.replicas}}"
    publish:
      - published_port: "{{bank_app.port}}"
        target_port: "{{bank_app.port}}"
        protocol: "tcp"
    force_update: yes
  when: bank_app.switch == "on" and inventory_hostname in groups.swarm_manager_prime
