# ---

# HLF CLI Service
  
  # Stop all Services services
- name: Stop CLI Service
  become: yes
  docker_swarm_service:   
    name: "{{item.name}}_cli"
    state: absent
    networks:
      - "{{swarm_network}}"
    loop: "{{ peerservices }}"
    
- name: Create CLI assets folders in hlft-store
  become: yes
  file: 
    path: "/root/hlft-store/{{item.name}}_cli"
    state: directory
    mode: 0750              
  loop: "{{ peerservices }}"

# Copy the relevent scripts
- name: Copy scripts
  become: yes
  copy:
    src: "cli.sh"
    dest: "/root/hlft-store/{{item.name}}_cli/cli.sh"
    mode: "0500"
    force: yes 
  loop: "{{ peerservices }}"

  # Create & Start service for CLI 
- name: Fabric Service - {{ item.name }}
  become: yes
  docker_swarm_service:
    name: "{{item.name}}_cli"
    hostname: "{{item.name}}_cli"
    networks:
      - "{{swarm_network}}"
    image: "{{cli.image}}:{{cli.tag}}"
    command: >
      bash -c "/root/{{item.name}}_cli/cli.sh;"
    working_dir: /root/{{item.name}}_cli
    mounts:      
      - source: "/root/hlft-store/{{item.name}}_cli/"
        target: "/root/{{item.name}}"
        type: bind 
      - source: "/root/hlft-store/orderer_cli/"
        target: "/root/{{item.name}}_cli/artifacts"
        type: bind
      - source: "/root/hlft-store/{{item.name}}/"
        target: "{{item.path}}"
        type: bind       
      - source: "/root/hlft-store/{{orgca.name}}/{{admin_user}}/"
        target: "/root/{{admin_user}}"
        type: bind
    env: 
      - "IDX={{idx}}"
      - "GOPATH=/opt/gopath"
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - "FABRIC_LOGGING_SPEC=DEBUG"
      - "CORE_PEER_TLS_ENABLED=true"  
      - "CORE_PEER_LOCALMSPID={{org.name}}MSP"    
      - "TLSCA_HOST={{tlsca.name}}"
      - "ORDERER_HOST={{orderer.name}}"
      - "AGENT_HOST={{item.name}}" 
      - "ADMIN_USER={{admin_user}}"           
    placement:      
      constraints:
        - node.role == worker      
    force_update: yes    
    loop: "{{ peerservices }}"
    loop_control:
      index_var: idx
  when: cli.switch == "on"