---

- name: Set GOPATH ENV variable
  lineinfile: 
    dest: /home/{{hlf_username}}/.bashrc
    insertafter: EOF
    line: "export GOPATH=/home/{{hlf_username}}/go"

- name: Creates GOPATH directory
  file:
    path: /home/{{hlf_username}}/go
    state: directory
    owner: "{{hlf_username}}"
    group: "{{hlf_group}}"
    mode: 0775