# ---

# HLF CLI Service

- name: Create chaincodes folders in hlft-store
  become: yes
  file: 
    path: "/root/hlft-store/chaincodes"
    state: directory
    mode: 0750

- name: Copy the local test chaincode folder
  become: yes
  copy: 
    src: "test_chaincode/"
    dest: "/root/hlft-store/chaincodes/test_chaincode"
    mode: 0750
                
  # Create & Start service for CLI 
- name: Fabric Service - {{ item.name }}
  become: yes
  docker_swarm_service:
    name: "CLI"
    hostname: "CLI"
    networks:
      - "{{swarm_network}}"
    image: "{{cli.image}}:{{cli.tag}}"
    command: >
      bash -c "while true; do sleep 2; done;"
    working_dir: /root/CLI
    mounts:     
      - source: "/root/hlft-store"
        target: "/root/CLI"
        type: bind      
    env: 
      - "GOPATH=/opt/gopath"
      - "CORE_VM_ENDPOINT=unix:///var/run/docker.sock"
      - "CORE_PEER_TLS_ENABLED=true"  
      - "CORE_PEER_LOCALMSPID={{org.name}}MSP"    
      - "ORDERER_HOST={{orderer.name}}"
      - "PEER1_HOST={{peer1.name}}"
      - "PEER2_HOST={{peer2.name}}"
      - "TLSCA_HOST={{tlsca.name}}"
      - "ORGCA_HOST={{tlsca.name}}"
    placement:      
      constraints:
        - node.role == worker      
    force_update: yes    
  when: cli.switch == "on"