# ---

# HLF CA Services  with
  # 1. 3x CouchDB Services 
  # 2. 1x for Endorser Peer [replicas=2]
  # 3. 1x for Commiter Peer [replicas=2]
  # 4. 1x for Anchor Peer [replicas=2]
  
  # Stop all Services services
- name: Stop CouchDB Service - {{ item.name }}
  become: yes
  become_user: "{{ hlf_username}}"
  docker_swarm_service:   
    name: "{{ item.name }}"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop:   
    - "{{ epeerdb }}"    
    - "{{ cpeerdb }}"    
    - "{{ apeerdb }}"  

  # We create relevent folder structure in S3FS mount locally for service 
- name: Clean CouchDB folders in hlft-store, if they exists
  become: yes  
  file: 
    path: "{{item.path}}"
    state: absent
  loop:        
    - "{{ epeerdb }}"    
    - "{{ cpeerdb }}"    
    - "{{ apeerdb }}"    
    
- name: Create CouchDB Server folders in hlft-store
  become: yes
  file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0750
  loop:
    - "{{ epeerdb }}"    
    - "{{ cpeerdb }}"    
    - "{{ apeerdb }}"

  # Create & Start services for CouchDBs
- name: Fabric Service - {{ item }}
  become: yes
  become_user: "{{ hlf_username}}"
  docker_swarm_service:
    user: "{{ item.name }}"     
    name: "{{ item.name }}"
    hostname: "{{ item.name }}"
    networks:
      - "{{swarm_network}}"
    image: "{{item.name}}:{{item.tag}}"
    mode: replicated
    replicas: "{{item.replicas}}"
    publish:
      - published_port: "{{item.port}}"
        target_port: "5984"
        protocol: "tcp"
    command: "bash -c"
    mounts:
      - source: "/home/{{ hlf_username}}/hlft-store/{{item.name}}"
        target: "/opt/couchdb/data"
        type: bind
    env:
      - "COUCHDB_USER={{item.name}}"
      - "COUCHDB_PASSWORD={{couchdb_password[item.name]}}"
    args:
      - "{{item.commands}}"
    placement:      
      constraints:
        - node.role == worker      
    force_update: yes
  loop: 
    - "{{ epeerdb }}"    
    # - "{{ cpeerdb }}"    
    # - "{{ apeerdb }}"