---

# Pull all relevent HLF images that would be used to create docker services, build them according to reqirements and commit them locally to each node

 - name: Stop & Remove Container {{ item.name }}, if it exist
   become: yes
   become_user: "root"
   docker_container:
     name: "{{ item.name }}"
     state: absent
   with_items:
    - "{{services}}"

 - name: Pull & Build Docker Image {{ item.image }}:{{ item.tag }}
   become: yes
   become_user: "root"
   docker_container:
      name: "{{ item.name }}"
      image: "{{ item.image }}:{{ item.tag }}"
      state: started
   with_items:
    - "{{services}}" 
    
    
 - name: Stop & Remove Container {{item.name}}, if it exist
   become: yes
   become_user: "root"
   docker_container:
     name: "{{item.name}}"
     state: absent
   with_items:
    - "{{services}}"