---

# Additional pakages to be installed
debian_package_list:
  - apt-transport-https
  - ca-certificates 
  - curl 
  - gnupg2 
  - software-properties-common
  - jq
  - rsync
  - golang-go
  - libtool
  - libltdl-dev
  - python3-pip
  - glusterfs-client

redhat_package_list:
  - yum-utils
  - device-mapper-persistent-data
  - lvm2
  #- epel-release # Needed for CentOS
  - jq
  - rsync
  - golang
  - libtool
  - libtool-ltdl-devel
  - python3-pip  
  - glusterfs-client

pip_packages:
  - docker

