---
- name: "Get docker info"
  shell: docker info
  register: docker_info
  changed_when: false


- name: "Create primary swarm manager"
  shell: docker swarm init --advertise-addr {{ ansible_eth0['ipv4']['address'] }}
  when: "docker_info.stdout.find('Swarm: inactive') != -1 and inventory_hostname in groups.swarm_manager_prime"

- name: "Get docker swarm manager token"
  shell: docker swarm join-token -q manager
  register: manager_token
  when: "inventory_hostname in groups.swarm_manager_prime"

- name: "Get docker swarm worker token"
  shell: docker swarm join-token -q worker
  register: worker_token
  when: "inventory_hostname in groups.swarm_manager_prime"

- name: "Join as a manager"
  shell: "docker swarm join --token {{ hostvars[groups.swarm_manager_prime[0]]['manager_token']['stdout'] }} {{ hostvars[groups.swarm_manager_prime[0]]['ansible_eth0']['ipv4']['address'] }}:2377"
  retries: 3
  delay: 20
  when: "docker_info.stdout.find('Swarm: inactive') != -1  and inventory_hostname in groups.swarm_managers"


- name: "Join as a worker"
  shell: "docker swarm join --token {{ hostvars[groups.swarm_manager_prime[0]]['worker_token']['stdout'] }} {{ hostvars[groups.swarm_manager_prime[0]]['ansible_eth0']['ipv4']['address'] }}:2377"
  retries: 3
  delay: 20
  when: "docker_info.stdout.find('Swarm: inactive') != -1 and inventory_hostname in groups.swarm_workers"