# ---

# HLF CA Services  with
  # 1. 1x Ordering Service [replica=2]
  
  # Stop all CA services
- name: Stop Orderer Service - {{ item.name }}
  become: yes
  become_user: "{{ hlf_username}}"
  docker_swarm_service:   
    name: "{{ item.name }}"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop: 
    - "{{ orderer }}"    

  # We create relevent folder structure in S3FS mount locally for service 
- name: Clean Orderer folders in hlft-store, if they exists
  become: yes  
  file: 
    path: "{{item.path}}"
    state: absent
  loop:        
    - "{{ orderer }}"
    
- name: Create Orderer CA Server folders in hlft-store
  become: yes
  file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0750
  loop:
        - "{{ orderer }}"

 # Copy relevent config files to s3fs directories for the docker services
- name: Config templating orderer.yaml
  become: yes
  vars:
    orderer_config: "{{item}}"
  template:
    src: orderer.yaml.j2
    dest: "/home/{{ hlf_username }}/hlft-store/{{item.name}}/orderer.yaml"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
    force: yes
  loop:
    - "{{ orderer }}"

 # Copy relevent config files to s3fs directories for the docker services
- name: Config templating configtx.yaml
  become: yes
  vars:
    orderer_config: "{{item}}"
  template:
    src: configtx.yaml.j2
    dest: "/home/{{ hlf_username }}/hlft-store/{{item.name}}/configtx.yaml"
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
    force: yes
  loop:
    - "{{ orderer }}"

- name: Ensures /home/{{ hlf_username}}/hlft-store/{{item.name}}/tls dir exists
  file: 
    path=/home/{{ hlf_username}}/hlft-store/{{item.name}}/tls 
    state=directory
  loop: 
    - "{{ orderer }}"

# Copy the root TLS certs from aica
- name: Copy TLS Cert
  become: yes
  copy:
    src: "/home/{{ hlf_username}}/hlft-store/{{item.caname}}/tls-cert.pem"
    dest: "/home/{{ hlf_username}}/hlft-store/{{item.name}}/tls/tls-{{item.caname}}-cert.pem"
    owner: "{{item.name}}"
    group: "{{item.group}}"
    mode: '0600'
    remote_src: yes
    force: yes
  loop: 
    - "{{ orderer }}"    

  # Create & Start service orderer with RAFT enabled
- name: Fabric Orderer with RAFT - {{ item }}
  become: yes
  become_user: "{{ hlf_username}}"   
  docker_swarm_service:
    user: "{{ item.name }}"     
    name: "{{ item.name }}"
    hostname: "{{ item.name }}"
    networks:
      - "{{swarm_network}}"
    image: "{{item.name}}:{{item.tag}}"
    mode: replicated
    replicas: "{{item.replicas}}"
    publish:
      - published_port: "{{item.port}}"
        target_port: "7050"
        protocol: "tcp"
    command: >
      bash -c "sleep 30000"
    mounts:
      - source: "/home/{{ hlf_username}}/hlft-store/{{item.name}}"
        target: "/home/{{item.name}}"
        type: bind
    env: 
      - "FABRIC_CFG_PATH=/home/{{item.name}}"
      - "ORDERER_USER={{item.name}}"
      - "ORDERER_USER={{orderer_password}}"
    placement:      
      constraints:
        - node.role == worker      
    force_update: yes
  loop: 
    - "{{ orderer }}"