# ---

# HLF CA Services  with
  # 1. 1x Ordering Service [replica=2]
  
  # Stop all CA services
- name: Stop Orderer Service - {{ item.name }}
  become: yes
  become_user: "{{ hlf_username}}"
  docker_swarm_service:   
    name: "{{ item.name }}"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop: 
    - "{{ orderer }}"    

  # We create relevent folder structure in S3FS mount locally for service 
- name: Clean Orderer folders in hlft-store, if they exists
  become: yes  
  file: 
    path: "{{item.path}}"
    state: absent
  loop:        
    - "{{ orderer }}"
    
- name: Create Orderer CA Server folders in hlft-store
  become: yes
  file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0750
  loop:
        - "{{ orderer }}"

  # Copy the relevent scripts
- name: Copy scripts
  become: yes
  copy:
    src: "{{item.0}}"
    dest: "/home/{{ hlf_username}}/hlft-store/{{orderer.name}}/{{item.0}}"
    owner: "{{orderer.name}}"
    group: "{{orderer.group}}"
    mode: "{{item.1}}"
    force: yes
  loop: 
    - ["orderer.sh", '0500']
    - ["bootstrap.sh", '0500']

- name: Copy MSP folder
  become: yes
  copy:
    src: "/home/{{ hlf_username}}/hlft-store/{{item.caname}}/client/{{item.name}}/"
    dest: "/home/{{ hlf_username}}/hlft-store/{{item.name}}/msp"
    owner: "{{item.name}}"
    group: "{{item.group}}"
    mode: '0750'
    remote_src: yes
    force: yes
  loop: 
    - "{{ orderer }}"   

 # Copy relevent config files to s3fs directories for the docker services
- name: Config templating orderer.yaml
  become: yes
  vars:
    orderer_config: "{{item[0]}}"
  template:
    src: "{{item[1]}}.j2"
    dest: "/home/{{ hlf_username }}/hlft-store/{{item[0].name}}/{{item[1]}}"
    owner: "{{ item[0].name }}"
    group: "{{ item[0].group }}"
    mode: 0600
    force: yes
  with_nested:
    - ["{{ orderer }}"]
    - ["orderer.yaml", "configtx.yaml"]

- name: Ensures /home/{{ hlf_username}}/hlft-store/{{item.name}}/tls dir exists
  file: 
    path: /home/{{ hlf_username}}/hlft-store/{{item.name}}/tls 
    state: directory
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0750
    force: yes    
  loop: 
    - "{{ orderer }}"

  # Create & Start service orderer with RAFT enabled
- name: Fabric Orderer with RAFT - {{ item }}
  become: yes
  become_user: "{{ hlf_username}}"   
  docker_swarm_service:
    user: "{{ item.name }}"     
    name: "{{ item.name }}"
    hostname: "{{ item.name }}"
    networks:
      - "{{swarm_network}}"
    image: "{{item.name}}:{{item.tag}}"
    mode: replicated
    replicas: "{{item.replicas}}"
    publish:
      - published_port: "{{item.port}}"
        target_port: "7050"
        protocol: "tcp"
    command: >
      bash -c "/home/{{item.name}}/{{item.name}}.sh;"
    mounts:
      - source: "/home/{{ hlf_username}}/hlft-store/{{item.name}}"
        target: "/home/{{item.name}}"
        type: bind
      - source: "/home/{{ hlf_username}}/hlft-store/{{item.caname}}/tls-cert.pem"
        target: "/home/{{item.name}}/tls/tls-{{item.caname}}-cert.pem"
        type: bind
    env: 
      - "FABRIC_CFG_PATH=/home/{{item.name}}"      
    placement:      
      constraints:
        - node.role == worker      
    force_update: yes
  loop: 
    - "{{ orderer }}"