---

# Setup GlusterFS as local mount on each node
# Install glusterfs-client
- name: Add new apt source
  become: yes
  apt_repository:
    repo: ppa:gluster/glusterfs-{{ glusterd_version }}
    filename: gluster.list
    state: present
  when: ansible_os_family == 'Debian'

  # Install glusterfs-clients
- name: Add an RPM signing key, uses whichever key is at the URL
  become: yes
  rpm_key:
    key: http://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/rsa.pub
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add new yum source
  yum_repository:
    name: glusterfs
    description: glusterfs YUM repo
    baseurl: https://download.gluster.org/pub/gluster/glusterfs/{{ glusterd_version }}/LATEST/RHEL/glusterfs-rhel8.repo
    state: present
  when: ansible_os_family == 'RedHat'

- name: Update repositories cache and install "glusterfs-client" and other required package
  become: yes
  package:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop:
    - "glusterfs-client"
  

# Check if GlusterFS is already mounted, if yes, unmount it
- name: Unmount GlusterFS if already mounted
  become: yes
  mount:
    path: /root/hlft-store
    state: unmounted

# Remove the local mount point folder, if it exists, so that we get the right permissions everytime
- name: Remove Mount Point
  become: yes
  file:
    path: /root/hlft-store
    state: absent

# Create the local mount point on each node for S3FS mount
- name: Create Mount Point
  become: yes
  become_user: "root"
  file:
    path: /root/hlft-store
    state: directory
    owner: "root"
    group: "root"
    mode: 0750

# Mount the volume on /root/myfiles
- name: Mount Gluster volume
  become: yes
  mount:
    path: /root/hlft-store
    src: "{{ gluster_cluster_host0 }}:/{{gluster_cluster_volume}}"
    fstype: glusterfs
    state: mounted