# ---

# HLF CA CLI Services

# Stop all CLI Services services
- name: Stop CLI Service - {{ orderer.name }}_cli
  become: yes
  docker_swarm_service:
    name: "{{ orderer.name }}_cli"
    state: absent
    networks:
      - "{{swarm_network}}"  


- name: Clean CLI orderer folder in hlft-store
  become: yes
  file: 
    path: "/root/hlft-store/{{orderer.name}}_cli"
    state: absent    

- name: Create CLI orderer folder in hlft-store
  become: yes
  file: 
    path: "/root/hlft-store/{{orderer.name}}_cli"
    state: directory
    mode: 0750              

# Copy the relevent scripts
- name: Copy scripts
  become: yes
  copy:
    src: "cli.sh"
    dest: "/root/hlft-store/{{orderer.name}}_cli/cli.sh"
    mode: "0500"
    force: yes  

  # Copy relevent config files to mount directories for the docker services
- name: Config templating configtx.yaml
  become: yes
  template:
    src: "configtx.yaml.j2"
    dest: "/root/hlft-store/{{orderer.name}}_cli/configtx.yaml"
    mode: 0660
    force: yes  

  # Create & Start service for CLI
- name: Fabric Service - {{ orderer.name }}
  become: yes
  docker_swarm_service:
    name: "{{ orderer.name }}_cli"
    hostname: "{{ orderer.name }}_cli"
    networks:
      - "{{swarm_network}}"
    image: "{{cli.image}}:{{cli.tag}}"
    mode: replicated
    replicas: "-1"
    command: >
      bash -c "/root/{{orderer.name}}_cli/cli.sh;"
    mounts:
      - source: "/root/hlft-store/{{orgca.name}}/{{orderer.name}}/msp"
        target: "{{orderer.path}}/msp"
        type: bind
      - source: "/root/hlft-store/{{tlsca.name}}/{{orderer.name}}/tls-msp"
        target: "{{orderer.path}}/tls-msp"
        type: bind
      - source: "/root/hlft-store/{{orderer.name}}_cli/"
        target: "/root/{{orderer.name}}_cli"
        type: bind
    env:
      - "HOST_HOME=/root/{{orderer.name}}_cli"
      - "ORG={{org.name}}"
    working_dir: "/root/{{orderer.name}}_cli"
    placement:
      constraints:
        - node.role == worker
    force_update: yes  
  when: orderer.switch == "on"

# Pause for 5 seconds for genesis block to be created.
- pause:
    seconds: 5
