# ---

# HLF CA CLI Services
  
# Stop all CLI Services services
- name: Stop CLI Service - {{ item.name }}_cli
  become: yes
  docker_swarm_service:   
    name: "{{ item.name }}_cli"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop: "{{ caservices }}"      

# Copy the relevent scripts
- name: Copy scripts
  become: yes
  copy:
    src: "cli.sh"
    dest: "/root/hlft-store/{{item.name}}/cli.sh"
    mode: "0500"
    force: yes
  loop: "{{ caservices }}"

  # Enroll Admin on each CA service
- name: ENROLL ADMIN Fabric Service - {{ item.name }}
  become: yes
  docker_swarm_service:
    name: "{{ item.name }}_cli"
    hostname: "{{ item.name }}_cli"
    networks:
      - "{{swarm_network}}"
    image: "{{item.image}}:{{item.tag}}"
    mode: replicated
    replicas: "-1"
    command: >
      bash -c "/{{item.path}}/enroll_admin.sh {{item.name}};"
    mounts:
      - source: "/root/hlft-store/{{item.name}}/"
        target: "{{item.path}}"
        type: bind     
    env: 
      - "HOST_HOME={{item.path}}"
      - "FABRIC_CA_NAME={{item.name}}"
      - "FABRIC_CA_SECRET={{item.password}}"
      - "FABRIC_CA_PORT=7054"
      - "CORE_PEER_LOCALMSPID={{org.name}}MSP"
      # - "ORDERER_HOST={{orderer.name}}"
      # - "ORDERER_SECRET={{orderer.password}}"
      # - "PEER_HOST={{peer.name}}"
      # - "PEER_SECRET={{peer.password}}"
    placement:      
      constraints:
        - node.role == worker     
    force_update: yes 
  loop: "{{ caservices }}" 
  when: item.switch == "on"