# ---

# HLF CA CLI Services

# Stop all CLI Services services
- name: Stop CLI Service - {{ item.name }}_cli
  become: yes
  docker_swarm_service:
    name: "{{ item.name }}_cli"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop: "{{ caservices }}"

# Copy the relevent scripts
- name: Copy scripts
  become: yes
  copy:
    src: "cli.sh"
    dest: "/root/hlft-store/{{item.name}}/cli.sh"
    mode: "0500"
    force: yes
  loop: "{{ caservices }}"

  # Enroll Root Admin on each CA service
- name: ENROLL Root ADMIN Fabric Service - {{ item.name }}
  become: yes
  docker_swarm_service:
    name: "{{ item.name }}_cli"
    hostname: "{{ item.name }}_cli"
    networks:
      - "{{swarm_network}}"
    image: "{{item.image}}:{{item.tag}}"
    mode: replicated
    replicas: "-1"
    command: >
      bash -c "/{{item.path}}/enroll_admin.sh {{idx}} {{item[0].type}};"
    mounts:
      - source: "/root/hlft-store/{{item[0].name}}/"
        target: "{{item[0].path}}"
        type: bind
    env:
      - "IDX={{item.1.0}}"
      - "HOST_HOME={{item.0.path}}"
      - "FABRIC_CA_NAME={{item.0.name}}"
      - "FABRIC_CA_SECRET={{item.0.password}}"
      - "FABRIC_CA_PORT=7054"
      - "CORE_PEER_LOCALMSPID={{org.name}}MSP"
      - "AGENT_HOST={{item.1.1.name}}"
      - "AGENT_SECRET={{item.1.1.password}}"
      - "AGENT_TYPE={{item.1.1.type}}"
    placement:
      constraints:
        - node.role == worker
    force_update: yes
  loop: "{{caservices | product(peerservices|enumerate) | list}}"
  when: item.switch == "on"
