# ---   
  # Stop Portainer service
- name: Stop Portainer Service - {{ item.name }}
  become: yes
  docker_swarm_service:   
    name: "{{item.name}}"
    state: absent
    networks:
      - "{{swarm_network}}"
  loop: 
    - "{{portainer}}"
  when: portainer.switch == "on"



  

  # Create & Start Portainer service
  # Containers are placed in the managers
- name: Portainer Service
  become: yes
  docker_swarm_service:
    name: "{{portainer.name}}"
    hostname: "{{portainer.name}}"
    networks:
      - "{{swarm_network}}"
    image: "{{portainer.image}}:{{portainer.tag}}"
    mode: replicated
    replicas: "{{portainer.replicas}}"
    mounts:
      - source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        type: bind 
      # - source: "/root/portainer/data"
      #   target: "/data"
      #   type: bind  
     
    publish:
      - published_port: "{{portainer.port}}"
        target_port: "9000"
        protocol: "tcp"
      # - published_port: "8000"
      #   target_port: "8000"
      #   protocol: "tcp"
      
    placement:      
      constraints:
        - node.role == manager
    force_update: yes
    debug : yes
  loop: 
    - "{{portainer}}" 
  when: portainer.switch == "on"