---

# Setup docker on each node
  # Setup docker repos
- name: Set up the Docker CE APT GPG key
  become: yes
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Set up the Docker CE APT repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    state: present
  when: ansible_os_family == 'Debian'

- name: Set up the Docker CE YUM repository
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  when: ansible_os_family == 'RedHat'

  # Install docker on each machine and start the service
- name: Install Docker
  become: yes
  package:
    name: docker-ce
    state: present
    update_cache: yes

