
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:
  grafana-storage:
  prometheus-storage:

networks:
  hlfnet:
    external:
      name: hlfnet

services:

  explorerdb.hlfnet:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.hlfnet
    hostname: explorerdb.hlfnet
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    volumes:
      - /root/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
      - pgdata:/var/lib/postgresql/data
    networks:
      - hlfnet

  explorer.hlfnet:
    image: hyperledger/explorer:latest
    container_name: explorer.hlfnet
    hostname: explorer.hlfnet
    environment:
      - DATABASE_HOST=explorerdb.hlfnet
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - /root/net1/config.json:/opt/explorer/app/platform/fabric/config.json
      - /root/net1/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - /root/hlft-store:/tmp/crypto
      #- walletstore:/opt/wallet
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    ports:
      - 8090:8080
    networks:
      - hlfnet
