---

# ansible-playbook -v 200.deploy_registrar_service.yml -u root

- name: Deploy Registrar Service
  hosts: all
  gather_facts: no
  tasks:  
    - name: Clean Registrar Folder Structure
      file:
        path: "/root/hlft-store/{{registrar.name}}"
        state: absent

    - name: Create Registrar Folder Structure
      file:
        path: "/root/hlft-store/{{Registrar.name}}"
        state: directory

    - name: Copy required scripts
      copy:
        src: "{{item}}"
        dest: "/root/hlft-store/{{Registrar.name}}/{{item}}"
      loop:
        - server.js
        - package.json
        - config/
      
    - name: Start the Registrar Service
      become: yes
      docker_swarm_service:
        name: "{{ registrar.name }}"
        hostname: "{{ registrar.name }}"
        networks:
          - "{{swarm_network}}"
        image: "{{registrar.image}}:{{registrar.tag}}"
        mode: replicated
        replicas: "{{registrar.replicas}}"        
        mounts:
          - source: "/root/hlft-store/{{registrar.name}}"
            target: "{{registrar.path}}"
            type: bind       
        publish:
          - published_port: "{{registrar.port}}"
            target_port: "8080"
            protocol: "tcp"
        working_dir: "{{registrar.path}}"
        command: >
          sh -c "sleep 30000s;"
        placement:      
          constraints:
            - node.role == worker      
        force_update: yes        